const translations = {
  en: {
    pageTitle_home: "VTuberForge - Home", pageTitle_login: "VTuberForge - Login", pageTitle_register: "VTuberForge - Register", pageTitle_lessons: "VTuberForge - Lessons", pageTitle_news: "VTuberForge - News", pageTitle_profile: "VTuberForge - Profile", pageTitle_admin: "VTuberForge - Admin", "pageTitle_try-vtuber": "VTuberForge - Try VTuber",
    brandSubtitle: "Learning platform", navHome: "Home", navLogin: "Login", navRegister: "Register", navLessons: "Lessons", navNews: "News", navProfile: "Profile", navAdmin: "Admin", navLogout: "Logout",
    heroKicker: "VTuber creator academy by AITU", heroTitle: 'Forge your virtual identity <span class="gradient-text">and go live like a pro</span>.', heroSubtitle: "Learn avatar creation, OBS setup, streaming confidence, visual branding, and the tech workflow behind modern VTubing.", ctaTryVtuber: "Try becoming a VTuber", ctaStart: "Start the forge", ctaLogin: "Enter lab", ctaContinue: "Continue learning",
    statTracks: "Creator tracks from avatar basics to full stream production.", statAccess: "Role-based access for students, creators, and admins.", statSync: "Tap to pass lessons and sync progress with the backend.", holoLive: "Live-ready", holoCreator: "Creator mode",
    whatLabel: "What you unlock", whatTitle: "A futuristic creator hub with real learning flow.", whatText: "VTuberForge feels like a digital studio: clear structure, protected pages, lesson progress, and a premium academic-tech atmosphere.", featureAccessTitle: "Smart access", featureAccessText: "Guests see the welcome path. Students enter lessons. Admin tools stay locked behind role checks.", featureRoadmapTitle: "Studio roadmap", featureRoadmapText: "Lessons are grouped into intro videos and full tutorial series, so every step feels clear and cinematic.", featureProgressTitle: "Progress sync", featureProgressText: "Completed courses connect to the backend API and show up across profile and lesson cards.",
    aboutLabel: "About us", aboutTitle: "Meet the team behind VTuberForge.", aboutText: "We are a small creator-focused team from Astana IT University building a practical space for future VTubers. Our goal is simple: help beginners understand the tools, design their avatar identity, and feel confident before their first real stream.", ariRole: "VTuber Consultant", ariText: "VTuber and 3D artist. Ari works as the friendly VTubing consultant: she helps students choose a character concept, understand stream culture, plan first content ideas, and avoid beginner mistakes.", bekaRole: "Tech & Tools Expert", bekaText: "Software engineer turned VTuber educator. Beka handles the technical side: OBS scenes, VSeeFace, tracking, microphone setup, plugins, and clean explanations for tools that usually feel confusing.", dideRole: "Art & Design Lead", dideText: "Professional 2D/3D character designer. Dide guides the visual side: VRoid Studio, Blender basics, color palettes, avatar personality, expressions, and small design choices that make a model memorable.", point1: "OBS scenes, overlays, audio, and stream polish", point2: "2D/3D avatar workflow from idea to presentation", point3: "Creator growth, content planning, and personal branding",
    loginLabel: "Sign in", loginTitle: "Welcome back", loginText: "Use your account to access lessons, news, and your profile.", inputLogin: "Login", inputPassword: "Password", loginButton: "Login",
    registerLabel: "Create account", registerTitle: "Join the platform", registerText: "Registration creates your user, generates tokens, and sends you straight into learning.", registerButton: "Create account",
    lessonsLabel: "Watch & learn", lessonsTitle: "Video Library", lessonsText: 'Lessons are split into two visual categories: <strong>Introduction Videos</strong> and <strong>Full Tutorial Series</strong>.', introVideos: "Introduction Videos", fullSeries: "Full Tutorial Series",
    lessonFullCourse: "FULL COURSE", lessonIntro: "INTRO", lessonCompleted: "COMPLETED", lessonWatch: "Watch on YouTube", lessonAlreadyCompleted: "Already completed", lessonMarkCompleted: "Mark as Completed", noIntroLessons: "No intro lessons yet.", noFullLessons: "No full courses yet.",
    newsLabel: "Newsroom", newsTitle: "Platform News & Updates", newsText: "A more interesting news layout with a featured update, then a feed of live cards.", featuredUpdate: "Featured update", newsFeature1: "Fresh lesson releases and platform updates.", newsFeature2: "Fast announcements for VTuber students and admins.", newsFeature3: "Stylish cards, clear structure, no clutter.", noNews: "No news yet.", noMoreNews: "No more news items yet.", newsUpdate: "Update", newsBulletin: "VTuberForge bulletin", newsLive: "Live",
    profileLabel: "Your profile", profileTitle: "Progress Dashboard", profileRoleLabel: "Role:", profileLearner: "Learner", profileTracked: "Progress tracked", profileLastTitle: "Last completed lesson", profileCompletedTitle: "Completed courses", profileFinished: "finished lesson(s)", profileListTitle: "Completed list", profileTipTitle: "Tip", profileTipText: 'Open the lessons page and click <strong>Mark as Completed</strong> after you finish a course. Your profile will update immediately.', profileLoading: "Loading...", profileNoCompleted: "No completed lessons yet", profileNoLessons: "You have not completed any lessons yet.",
    adminLabel: "Admin only", adminTitle: "Control Panel", adminText: "This page is hidden from normal users in the navbar and protected by route checks.", adminCreateLesson: "Create lesson", adminLessonTitlePh: "Lesson title", adminLessonDescPh: "Lesson description", adminIntroOption: "Intro", adminFullOption: "Full Course", adminYoutubePh: "YouTube link", adminCreateLessonButton: "Create lesson", adminCreateNews: "Create news", adminNewsTitlePh: "News title", adminNewsContentPh: "News content", adminCreateNewsButton: "Create news", adminCurrentLessons: "Current lessons", adminCurrentNews: "Current news", adminNoLessons: "No lessons yet.", adminNoNews: "No news yet.", adminDelete: "Delete",
    toastMissingData: "Missing data", toastLoginPassword: "Please enter login and password.", toastLoginFailed: "Login failed", toastWelcomeBack: "Welcome back", toastLoginSuccess: "Login successful.", toastRegistrationFailed: "Registration failed", toastAccountCreated: "Account created", toastRegisterSuccess: "Registration successful.", toastNotLoggedIn: "Not logged in", toastSignInAgain: "Please sign in again.", toastCantMark: "Can't mark lesson", toastCompleted: "Completed", toastLessonPassed: "Lesson marked as passed.", toastError: "Error", toastLessonCreated: "Lesson created", toastLessonAdded: "New lesson added.", toastLessonDeleted: "Lesson deleted", toastRemoved: "Removed successfully.", toastNewsCreated: "News created", toastNewsAdded: "Announcement added.", toastNewsDeleted: "News deleted", toastProfileError: "Profile error", toastFillLesson: "Fill all lesson fields.", toastFillNews: "Enter title and content.", confirmDeleteLesson: "Delete this lesson?", confirmDeleteNews: "Delete this news item?",
    tryLabel: "Live avatar test", tryTitle: "Try becoming a VTuber", tryText: "Upload a VRM, GLB, or GLTF model, turn on your camera, and watch the avatar follow your head movement and facial expressions.", tryEmptyTitle: "Upload a 3D model", tryEmptyText: "VRM, GLB, or GLTF works best.", tryUploadLabel: "3D model file", tryCameraButton: "Start camera", tryResetButton: "Reset pose", tryStatusLabel: "Status", tryStatusIdle: "Waiting for model", tryStatusLoadingTracker: "Loading face tracker", tryStatusLoadingModel: "Loading model", tryStatusTracking: "Tracking enabled", tryStatusCameraError: "Camera unavailable", tryStatusModelReadyFace: "Model loaded with face morphs", tryStatusModelReadyBasic: "Model loaded, basic motion only", tryStatusModelError: "Could not load model", tryFaceLabel: "Face tracking", tryFaceOff: "Off", tryFaceOn: "Face detected", tryFaceSearching: "Searching", tryModelLabel: "Model", tryModelEmpty: "Not loaded", tryNoteTitle: "Important", tryNoteText: "Facial mimic works best on VRM models or GLB models with morph targets named like blink, smile, jawOpen, or mouthOpen.", footerBrand: "VTuberForge x Astana IT University", footerBackend: "Frontend connected to Go backend"
  },
  kk: {
    pageTitle_home: "VTuberForge - Басты бет", pageTitle_login: "VTuberForge - Кіру", pageTitle_register: "VTuberForge - Тіркелу", pageTitle_lessons: "VTuberForge - Сабақтар", pageTitle_news: "VTuberForge - Жаңалықтар", pageTitle_profile: "VTuberForge - Профиль", pageTitle_admin: "VTuberForge - Админ", "pageTitle_try-vtuber": "VTuberForge - VTuber сынағы",
    brandSubtitle: "Оқу платформасы", navHome: "Басты бет", navLogin: "Кіру", navRegister: "Тіркелу", navLessons: "Сабақтар", navNews: "Жаңалықтар", navProfile: "Профиль", navAdmin: "Админ", navLogout: "Шығу",
    heroKicker: "AITU қолдауындағы VTuber creator academy", heroTitle: 'Өз виртуалды бейнеңді жаса <span class="gradient-text">және эфирге кәсіби шық</span>.', heroSubtitle: "Аватар жасауды, OBS баптауды, стримге сенімді шығуды, визуалды бренд құруды және заманауи VTubing технологиясын үйрен.", ctaTryVtuber: "VTuber болып көру", ctaStart: "Forge бастау", ctaLogin: "Lab-қа кіру", ctaContinue: "Оқуды жалғастыру",
    statTracks: "Аватар негізінен толық stream production-ға дейінгі creator tracks.", statAccess: "Студенттер, креаторлар және админдер үшін role-based access.", statSync: "Сабақты аяқтап, прогресті backend-пен синхрондау.", holoLive: "Эфирге дайын", holoCreator: "Creator mode",
    whatLabel: "Не ашылады", whatTitle: "Нақты learning flow бар футуристік creator hub.", whatText: "VTuberForge digital studio сияқты сезіледі: нақты құрылым, қорғалған беттер, сабақ прогресі және premium academic-tech атмосфера.", featureAccessTitle: "Smart access", featureAccessText: "Қонақтар welcome path көреді. Студенттер сабақтарға кіреді. Admin tools role checks арқылы қорғалады.", featureRoadmapTitle: "Studio roadmap", featureRoadmapText: "Сабақтар intro videos және full tutorial series болып бөлінеді, сондықтан әр қадам түсінікті және cinematic.", featureProgressTitle: "Progress sync", featureProgressText: "Аяқталған курстар backend API-ға қосылып, profile және lesson cards ішінде көрінеді.",
    aboutLabel: "Біз туралы", aboutTitle: "VTuberForge командасымен танысыңыз.", aboutText: "Біз Astana IT University ішіндегі future VTubers үшін практикалық кеңістік жасап жатқан шағын creator-focused командамыз. Мақсатымыз қарапайым: жаңадан бастаушыларға tools түсінуге, avatar identity құруға және алғашқы stream алдында сенімді болуға көмектесу.", ariRole: "VTuber кеңесшісі", ariText: "VTuber және 3D artist. Ari friendly VTubing consultant ретінде көмектеседі: character concept таңдаудан бастап, stream culture түсінуге, алғашқы content ideas жоспарлауға және beginner mistakes болдырмауға дейін.", bekaRole: "Tech & Tools Expert", bekaText: "Software engineer және VTuber educator. Beka техникалық бөлікті жүргізеді: OBS scenes, VSeeFace, tracking, microphone setup, plugins және әдетте қиын көрінетін tools-ты түсінікті етіп түсіндіру.", dideRole: "Art & Design Lead", dideText: "Кәсіби 2D/3D character designer. Dide visual бағытты жүргізеді: VRoid Studio, Blender basics, color palettes, avatar personality, expressions және модельді есте қаларлық ететін шағын design choices.", point1: "OBS scenes, overlays, audio және stream polish", point2: "Идеядан презентацияға дейінгі 2D/3D avatar workflow", point3: "Creator growth, content planning және personal branding",
    loginLabel: "Кіру", loginTitle: "Қайта қош келдіңіз", loginText: "Сабақтарға, жаңалықтарға және профиліңізге кіру үшін аккаунтыңызды пайдаланыңыз.", inputLogin: "Логин", inputPassword: "Құпия сөз", loginButton: "Кіру",
    registerLabel: "Аккаунт жасау", registerTitle: "Платформаға қосылыңыз", registerText: "Тіркелу user жасайды, tokens береді және сізді бірден оқуға өткізеді.", registerButton: "Аккаунт жасау",
    lessonsLabel: "Көр және үйрен", lessonsTitle: "Видео кітапхана", lessonsText: 'Сабақтар екі визуалды бөлімге бөлінген: <strong>Кіріспе видеолар</strong> және <strong>Толық tutorial series</strong>.', introVideos: "Кіріспе видеолар", fullSeries: "Толық tutorial series",
    lessonFullCourse: "ТОЛЫҚ КУРС", lessonIntro: "КІРІСПЕ", lessonCompleted: "АЯҚТАЛДЫ", lessonWatch: "YouTube-та көру", lessonAlreadyCompleted: "Бұрын аяқталған", lessonMarkCompleted: "Аяқталды деп белгілеу", noIntroLessons: "Кіріспе сабақтар әлі жоқ.", noFullLessons: "Толық курстар әлі жоқ.",
    newsLabel: "Жаңалықтар", newsTitle: "Платформа жаңалықтары", newsText: "Featured update және live cards feed бар қызығырақ news layout.", featuredUpdate: "Басты жаңалық", newsFeature1: "Жаңа сабақтар мен platform updates.", newsFeature2: "VTuber students және admins үшін жылдам хабарландырулар.", newsFeature3: "Стильді cards, анық құрылым, артық clutter жоқ.", noNews: "Жаңалықтар әлі жоқ.", noMoreNews: "Басқа жаңалықтар әзірге жоқ.", newsUpdate: "Жаңарту", newsBulletin: "VTuberForge хабаршысы", newsLive: "Live",
    profileLabel: "Сіздің профиль", profileTitle: "Прогресс dashboard", profileRoleLabel: "Рөл:", profileLearner: "Оқушы", profileTracked: "Прогресс сақталады", profileLastTitle: "Соңғы аяқталған сабақ", profileCompletedTitle: "Аяқталған курстар", profileFinished: "аяқталған сабақ", profileListTitle: "Аяқталғандар тізімі", profileTipTitle: "Кеңес", profileTipText: 'Курсты бітіргеннен кейін lessons page ашып, <strong>Аяқталды деп белгілеу</strong> батырмасын басыңыз. Профиль бірден жаңарады.', profileLoading: "Жүктелуде...", profileNoCompleted: "Әлі аяқталған сабақ жоқ", profileNoLessons: "Сіз әлі ешқандай сабақты аяқтамадыңыз.",
    adminLabel: "Тек админ", adminTitle: "Басқару панелі", adminText: "Бұл бет қарапайым users үшін navbar ішінде жасырылған және route checks арқылы қорғалған.", adminCreateLesson: "Сабақ жасау", adminLessonTitlePh: "Сабақ атауы", adminLessonDescPh: "Сабақ сипаттамасы", adminIntroOption: "Кіріспе", adminFullOption: "Толық курс", adminYoutubePh: "YouTube сілтемесі", adminCreateLessonButton: "Сабақ жасау", adminCreateNews: "Жаңалық жасау", adminNewsTitlePh: "Жаңалық атауы", adminNewsContentPh: "Жаңалық мәтіні", adminCreateNewsButton: "Жаңалық жасау", adminCurrentLessons: "Қазіргі сабақтар", adminCurrentNews: "Қазіргі жаңалықтар", adminNoLessons: "Сабақтар әлі жоқ.", adminNoNews: "Жаңалықтар әлі жоқ.", adminDelete: "Өшіру",
    toastMissingData: "Деректер жетіспейді", toastLoginPassword: "Логин мен құпия сөзді енгізіңіз.", toastLoginFailed: "Кіру сәтсіз", toastWelcomeBack: "Қош келдіңіз", toastLoginSuccess: "Кіру сәтті өтті.", toastRegistrationFailed: "Тіркелу сәтсіз", toastAccountCreated: "Аккаунт жасалды", toastRegisterSuccess: "Тіркелу сәтті өтті.", toastNotLoggedIn: "Жүйеге кірмегенсіз", toastSignInAgain: "Қайта кіріңіз.", toastCantMark: "Сабақты белгілеу мүмкін емес", toastCompleted: "Аяқталды", toastLessonPassed: "Сабақ өтті деп белгіленді.", toastError: "Қате", toastLessonCreated: "Сабақ жасалды", toastLessonAdded: "Жаңа сабақ қосылды.", toastLessonDeleted: "Сабақ өшірілді", toastRemoved: "Сәтті өшірілді.", toastNewsCreated: "Жаңалық жасалды", toastNewsAdded: "Хабарландыру қосылды.", toastNewsDeleted: "Жаңалық өшірілді", toastProfileError: "Профиль қатесі", toastFillLesson: "Барлық сабақ өрістерін толтырыңыз.", toastFillNews: "Атауы мен мәтінін енгізіңіз.", confirmDeleteLesson: "Бұл сабақты өшіру керек пе?", confirmDeleteNews: "Бұл жаңалықты өшіру керек пе?",
    tryLabel: "Live avatar сынағы", tryTitle: "VTuber болып көріңіз", tryText: "VRM, GLB немесе GLTF модель жүктеп, камераны қосыңыз. Avatar бас қозғалысыңызды және facial expressions қайталайды.", tryEmptyTitle: "3D модель жүктеңіз", tryEmptyText: "VRM, GLB немесе GLTF жақсы жұмыс істейді.", tryUploadLabel: "3D model file", tryCameraButton: "Камераны қосу", tryResetButton: "Позаны reset", tryStatusLabel: "Статус", tryStatusIdle: "Модель күтілуде", tryStatusLoadingTracker: "Face tracker жүктелуде", tryStatusLoadingModel: "Модель жүктелуде", tryStatusTracking: "Tracking қосылды", tryStatusCameraError: "Камера қолжетімсіз", tryStatusModelReadyFace: "Модель face morphs арқылы жүктелді", tryStatusModelReadyBasic: "Модель жүктелді, basic motion ғана", tryStatusModelError: "Модель жүктелмеді", tryFaceLabel: "Face tracking", tryFaceOff: "Өшірулі", tryFaceOn: "Бет табылды", tryFaceSearching: "Ізделуде", tryModelLabel: "Модель", tryModelEmpty: "Жүктелмеген", tryNoteTitle: "Маңызды", tryNoteText: "Facial mimic VRM немесе blink, smile, jawOpen, mouthOpen сияқты morph targets бар GLB модельдерде жақсы жұмыс істейді.", footerBrand: "VTuberForge x Astana IT University", footerBackend: "Frontend Go backend-пен қосылған"
  },
  ru: {
    pageTitle_home: "VTuberForge - Главная", pageTitle_login: "VTuberForge - Вход", pageTitle_register: "VTuberForge - Регистрация", pageTitle_lessons: "VTuberForge - Уроки", pageTitle_news: "VTuberForge - Новости", pageTitle_profile: "VTuberForge - Профиль", pageTitle_admin: "VTuberForge - Админ", "pageTitle_try-vtuber": "VTuberForge - Попробуй VTuber",
    brandSubtitle: "Обучающая платформа", navHome: "Главная", navLogin: "Войти", navRegister: "Регистрация", navLessons: "Уроки", navNews: "Новости", navProfile: "Профиль", navAdmin: "Админ", navLogout: "Выйти",
    heroKicker: "VTuber creator academy от AITU", heroTitle: 'Создай свою виртуальную личность <span class="gradient-text">и выходи в эфир как профи</span>.', heroSubtitle: "Изучи создание аватара, настройку OBS, уверенный стриминг, визуальный брендинг и технический workflow современного VTubing.", ctaTryVtuber: "Попробуй стать витубером", ctaStart: "Начать forge", ctaLogin: "Войти в lab", ctaContinue: "Продолжить обучение",
    statTracks: "Creator tracks от основ аватара до полноценного stream production.", statAccess: "Role-based access для студентов, креаторов и админов.", statSync: "Отмечай уроки как пройденные и синхронизируй прогресс с backend.", holoLive: "Готов к эфиру", holoCreator: "Creator mode",
    whatLabel: "Что внутри", whatTitle: "Футуристичный creator hub с настоящим learning flow.", whatText: "VTuberForge ощущается как digital studio: понятная структура, защищенные страницы, прогресс уроков и premium academic-tech атмосфера.", featureAccessTitle: "Smart access", featureAccessText: "Гости видят welcome path. Студенты переходят к урокам. Admin tools закрыты role checks.", featureRoadmapTitle: "Studio roadmap", featureRoadmapText: "Уроки разделены на intro videos и full tutorial series, поэтому каждый шаг понятный и cinematic.", featureProgressTitle: "Progress sync", featureProgressText: "Пройденные курсы подключаются к backend API и отображаются в profile и lesson cards.",
    aboutLabel: "О нас", aboutTitle: "Познакомьтесь с командой VTuberForge.", aboutText: "Мы небольшая creator-focused команда из Astana IT University, которая делает практичное пространство для будущих VTubers. Наша цель простая: помочь новичкам разобраться в инструментах, собрать avatar identity и уверенно подойти к первому настоящему стриму.", ariRole: "VTuber-консультант", ariText: "VTuber и 3D artist. Ari работает как дружелюбный VTubing consultant: помогает выбрать character concept, понять stream culture, придумать первые content ideas и избежать типичных ошибок новичка.", bekaRole: "Tech & Tools Expert", bekaText: "Software engineer, ставший VTuber educator. Beka отвечает за техническую часть: OBS scenes, VSeeFace, tracking, microphone setup, plugins и понятные объяснения tools, которые обычно кажутся сложными.", dideRole: "Art & Design Lead", dideText: "Профессиональный 2D/3D character designer. Dide ведет визуальную часть: VRoid Studio, Blender basics, color palettes, avatar personality, expressions и маленькие design choices, которые делают модель запоминающейся.", point1: "OBS scenes, overlays, audio и stream polish", point2: "2D/3D avatar workflow от идеи до презентации", point3: "Creator growth, content planning и personal branding",
    loginLabel: "Вход", loginTitle: "С возвращением", loginText: "Войдите в аккаунт, чтобы открыть уроки, новости и профиль.", inputLogin: "Логин", inputPassword: "Пароль", loginButton: "Войти",
    registerLabel: "Создать аккаунт", registerTitle: "Присоединяйся к платформе", registerText: "Регистрация создаст пользователя, выдаст токены и сразу отправит тебя к обучению.", registerButton: "Создать аккаунт",
    lessonsLabel: "Смотри и учись", lessonsTitle: "Видео библиотека", lessonsText: 'Уроки разделены на две визуальные категории: <strong>Вводные видео</strong> и <strong>Полные серии туториалов</strong>.', introVideos: "Вводные видео", fullSeries: "Полные серии туториалов",
    lessonFullCourse: "ПОЛНЫЙ КУРС", lessonIntro: "ВВОДНЫЙ", lessonCompleted: "ЗАВЕРШЕНО", lessonWatch: "Смотреть на YouTube", lessonAlreadyCompleted: "Уже завершено", lessonMarkCompleted: "Отметить как пройденное", noIntroLessons: "Вводных уроков пока нет.", noFullLessons: "Полных курсов пока нет.",
    newsLabel: "Новости", newsTitle: "Новости и обновления платформы", newsText: "Более интересная лента: главный апдейт и карточки свежих новостей.", featuredUpdate: "Главное обновление", newsFeature1: "Новые уроки и обновления платформы.", newsFeature2: "Быстрые объявления для VTuber-студентов и админов.", newsFeature3: "Стильные карточки, понятная структура, без лишнего шума.", noNews: "Новостей пока нет.", noMoreNews: "Больше новостей пока нет.", newsUpdate: "Обновление", newsBulletin: "Бюллетень VTuberForge", newsLive: "Live",
    profileLabel: "Твой профиль", profileTitle: "Панель прогресса", profileRoleLabel: "Роль:", profileLearner: "Ученик", profileTracked: "Прогресс отслеживается", profileLastTitle: "Последний завершенный урок", profileCompletedTitle: "Завершенные курсы", profileFinished: "завершенных урок(ов)", profileListTitle: "Список завершенных", profileTipTitle: "Совет", profileTipText: 'Открой страницу уроков и нажми <strong>Отметить как пройденное</strong> после завершения курса. Профиль обновится сразу.', profileLoading: "Загрузка...", profileNoCompleted: "Завершенных уроков пока нет", profileNoLessons: "Ты пока не завершил ни одного урока.",
    adminLabel: "Только админ", adminTitle: "Панель управления", adminText: "Эта страница скрыта от обычных пользователей в навигации и защищена проверками маршрута.", adminCreateLesson: "Создать урок", adminLessonTitlePh: "Название урока", adminLessonDescPh: "Описание урока", adminIntroOption: "Вводный", adminFullOption: "Полный курс", adminYoutubePh: "Ссылка YouTube", adminCreateLessonButton: "Создать урок", adminCreateNews: "Создать новость", adminNewsTitlePh: "Заголовок новости", adminNewsContentPh: "Текст новости", adminCreateNewsButton: "Создать новость", adminCurrentLessons: "Текущие уроки", adminCurrentNews: "Текущие новости", adminNoLessons: "Уроков пока нет.", adminNoNews: "Новостей пока нет.", adminDelete: "Удалить",
    toastMissingData: "Не хватает данных", toastLoginPassword: "Введите логин и пароль.", toastLoginFailed: "Вход не удался", toastWelcomeBack: "С возвращением", toastLoginSuccess: "Вход выполнен успешно.", toastRegistrationFailed: "Регистрация не удалась", toastAccountCreated: "Аккаунт создан", toastRegisterSuccess: "Регистрация прошла успешно.", toastNotLoggedIn: "Вы не вошли", toastSignInAgain: "Пожалуйста, войдите снова.", toastCantMark: "Не удалось отметить урок", toastCompleted: "Готово", toastLessonPassed: "Урок отмечен как пройденный.", toastError: "Ошибка", toastLessonCreated: "Урок создан", toastLessonAdded: "Новый урок добавлен.", toastLessonDeleted: "Урок удален", toastRemoved: "Успешно удалено.", toastNewsCreated: "Новость создана", toastNewsAdded: "Объявление добавлено.", toastNewsDeleted: "Новость удалена", toastProfileError: "Ошибка профиля", toastFillLesson: "Заполните все поля урока.", toastFillNews: "Введите заголовок и текст.", confirmDeleteLesson: "Удалить этот урок?", confirmDeleteNews: "Удалить эту новость?",
    tryLabel: "Тест live-аватара", tryTitle: "Попробуй стать витубером", tryText: "Загрузи VRM, GLB или GLTF модель, включи камеру и посмотри, как аватар повторяет движения головы и мимику.", tryEmptyTitle: "Загрузи 3D модель", tryEmptyText: "Лучше всего подходят VRM, GLB или GLTF.", tryUploadLabel: "Файл 3D модели", tryCameraButton: "Включить камеру", tryResetButton: "Сбросить позу", tryStatusLabel: "Статус", tryStatusIdle: "Ожидание модели", tryStatusLoadingTracker: "Загрузка face tracker", tryStatusLoadingModel: "Загрузка модели", tryStatusTracking: "Tracking включен", tryStatusCameraError: "Камера недоступна", tryStatusModelReadyFace: "Модель загружена с face morphs", tryStatusModelReadyBasic: "Модель загружена, только basic motion", tryStatusModelError: "Не удалось загрузить модель", tryFaceLabel: "Face tracking", tryFaceOff: "Выключен", tryFaceOn: "Лицо найдено", tryFaceSearching: "Поиск", tryModelLabel: "Модель", tryModelEmpty: "Не загружена", tryNoteTitle: "Важно", tryNoteText: "Мимика лучше всего работает на VRM или GLB моделях с morph targets вроде blink, smile, jawOpen или mouthOpen.", footerBrand: "VTuberForge x Astana IT University", footerBackend: "Frontend подключен к Go backend"
  }
};

function getCurrentLanguage() {
  return localStorage.getItem("vtuberforge-lang") || "en";
}

function t(key) {
  const lang = getCurrentLanguage();
  return translations[lang]?.[key] ?? translations.en[key] ?? key;
}

function setLanguage(lang) {
  const dictionary = translations[lang] || translations.en;
  const page = document.body?.dataset.page || "home";

  document.documentElement.lang = lang;
  document.title = dictionary[`pageTitle_${page}`] || dictionary.pageTitle_home || document.title;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key] !== undefined) element.textContent = dictionary[key];
  });

  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const key = element.dataset.i18nHtml;
    if (dictionary[key] !== undefined) element.innerHTML = dictionary[key];
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    const key = element.dataset.i18nPlaceholder;
    if (dictionary[key] !== undefined) element.setAttribute("placeholder", dictionary[key]);
  });

  document.querySelectorAll("[data-lang-btn]").forEach((button) => {
    button.classList.toggle("active", button.dataset.langBtn === lang);
  });

  localStorage.setItem("vtuberforge-lang", lang);
  window.dispatchEvent(new CustomEvent("vtuberforge:languagechange", { detail: { lang } }));
}

window.t = t;
window.setLanguage = setLanguage;
window.getCurrentLanguage = getCurrentLanguage;

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll("[data-lang-btn]").forEach((button) => {
    button.addEventListener("click", () => setLanguage(button.dataset.langBtn));
  });

  setLanguage(getCurrentLanguage());
});

